### ISSUE TITLE
Pontoon is not compatible with Python 3.10

### ISSUE THREAD

**Issue by flozz** [mozilla/pontoon#2493]
Hello,

When I try to run DB migrations with Python 3.10 I have the following error:

     ImportError: cannot import name 'MutableMapping' from 'collections' (/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/collections/__init__.py)

Importing things from `collection` already raises a warning with Python 3.9:

    DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

Full log available in this pipeline → https://github.com/wanadev/pontoon-debian/runs/6160315927?check_suite_focus=true

It seems that some dependencies should be updated or fixed :)

**Comment by flozz** [comment]
The issue seems te be located in `silme`:

https://hg.mozilla.org/l10n/silme/file/tip/lib/silme/core/types/lazydict.py#l26

**Comment by mathjazz** [comment]
We use our own silme fork, which should already work with python 3.10:
https://github.com/mozilla/silme/blob/master/lib/silme/core/types/lazydict.py#L26

We need to cut a new release and point Pontoon to it.
