### ISSUE TITLE
Profile page crashes when displayed by an anonymous user

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#4342]
For example, visit https://pontoon.mozilla.org/contributors/flod/ in a private window.

```python
jinja2.exceptions.UndefinedError: 'SimpleLazyObject object' has no attribute 'can_translate_locales'
```

`user.can_translate_locales()` is called without a guard. That method is attached to User via `add_to_class` (pontoon/base/models/user.py), so it doesn't exist on AnonymousUser. Other uses of the request user in the same template are already guarded with `user.is_authenticated`.

**Comment by flodolo** [comment]
This seems to be a regression from #4197.
